### ISSUE TITLE
Extra linebreak and inconsistent whitespace when columnifying html attributes.

### ISSUE THREAD

**Issue by gautelo** [emmetio/brackets-emmet#65]
With emmet as the only extension to brackets 1.0, I create an emtpy html-document and expand "!", place the cursor in the body and expand "div.stuff" or enter the <div class="stuff"></div> manually.

Place the cursor at the start of "class" and hit enter. I expect the class attribute to go one line down and get indented by one tab relative to the opening tag "<" character or indented to one space to the right of the opening "div" or some other consistent indentation that makes sense. 

What I get is one line of whitespace and the class alligning with the "<" character of the opening div. In short I hit enter once, but I get two linebreaks. The behaviour is the same regardless of my tab-scheme; "Tab Size: 4" or "Spaces: 2".

After fiddling around a bit with different html, the behaviour does not appear to be consistent. For some other html I don't get an extra line of space when trying to linebreak on attributes. The indentation is not consistent either. Sometimes I get the attribute aligning with the "<" character, as above, but sometimes I get one space in addition.

Why is this important? Because sometimes, especially when writing AngularJS code I need many attributes and to make my templates more readable it helps to allign the attributes in a column rather than to flow them on a single line.

For reference, when not using any addons, the default behaviour is that the class moves one line straight down with no change to the char-count meaning 1 newline and enough whitespace to place the "class" at the same column as it had before hitting enter.

Thanks for a great tool! ;)
##

**Comment by jrdnbwmn** [comment]
+1, I'm seeing the same behavior, and so is this guy:

http://stackoverflow.com/questions/27251080/fixing-brackets-indentation-new-line-indentation-off-by-one-space-or-tab

Sometimes I'll enter down and the char count for tabs is off by one (as shown in the gif that the above StackOverflow question has).

I've confirmed that this is an Emmet issue because reloading Brackets without extensions fixes the problem, and the only other extensions I have are for the file tree and handlebars syntax highlighting.

**Comment by gautelo** [comment]
This is really old by now. I don't know if the issue remains and I can't be bothered to check. :) So I'm closing this.
